# Generated by Django 3.2.5 on 2021-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSOTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_address', models.CharField(default='None', max_length=100)),
                ('email_address', models.EmailField(default='None', max_length=100)),
                ('landline', models.CharField(default='None', max_length=15)),
                ('fax', models.CharField(default='None', max_length=20)),
                ('cellphone', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('President', 'President')], max_length=20)),
                ('certificate', models.CharField(choices=[('Accreditation', 'Accreditation')], max_length=20)),
                ('dswd_certificate_accreditation_no', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField()),
                ('ga', models.CharField(max_length=10)),
                ('caap', models.CharField(max_length=100)),
            ],
        ),
    ]
